name: Vercel Deployments

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
    paths:
      - apps/web/**
      - apps/backoffice/**
      - packages/logger/**
      - packages/mode/**
      - packages/ui/**
      - packages/utils/**
      - .github/workflows/**

jobs:
  pr_comment:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add PR Comment
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            app URL:
            backoffice URL:
          message-id: vercel-urls

  deploy:
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        app_project_id: [ WEB_VERCEL_PROJECT_ID, BACKOFFICE_VERCEL_PROJECT_ID ]
    uses: ./.github/workflows/deploy-vercel-fn.yml
    secrets:
      database_url: ${{ secrets.DATABASE_URL }}
#      neon_api_key: ${{ secrets.NEON_API_KEY }}
#      neon_database_name: ${{ secrets.NEON_DATABASE_NAME }}
#      neon_database_username: ${{ secrets.NEON_DATABASE_USERNAME }}
#      neon_project_id: ${{ secrets.NEON_PROJECT_ID }}
      turbo_token: ${{ secrets.TURBO_TOKEN }}
      vercel_project_id: ${{ secrets[matrix.app_project_id] }}
      vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
    with:
      turbo_team: ${{ vars.turbo_team }}
      environment: ${{ matrix.app_project_id == 'WEB_VERCEL_PROJECT_ID' && 'app' || 'backoffice' }}
