name: Vercel Deployments

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - deploy-vercel
    paths:
      - apps/web/**
      - apps/backoffice/**
      - packages/logger/**
      - packages/mode/**
      - packages/ui/**
      - packages/utils/**
      - .github/workflows/**

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        app_project_id: [ WEB_VERCEL_PROJECT_ID, BACKOFFICE_VERCEL_PROJECT_ID ]
    uses: ./.github/workflows/deploy-vercel-fn.yml
    secrets:
      sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}
      turbo_token: ${{ secrets.TURBO_TOKEN }}
      vercel_project_id: ${{ secrets[matrix.app_project_id] }}
      vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
    with:
      turbo_team: ${{ vars.turbo_team }}
